version: '3.8'
services:
    
  app:
    build: ./app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    networks:
      - test
    volumes:
      - "./app/:/lab_3/app"
      - "./app/templates:/app/templates"
    restart: on-failure
      
  redis:
    image: redis
    networks:
      - test

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: pgAdmin@client.com
      PGADMIN_DEFAULT_PASSWORD: pgAdmin
    ports:
      - "5050:80"
    networks:
      - test

  db:
    image: postgres:14.1-alpine
    user: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
    networks:
      - test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:postgresql://db:5432/database -user=postgres -password=postgres -baselineOnMigrate=true migrate
    volumes:
      - "./sql:/flyway/sql"
    depends_on:
      - db
    networks:
      - test
    restart: on-failure
  
networks:
  test:
